version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: anlix_test_front
    ports:
      - 5173:5173
    restart: on-failure
    environment:
      - REACT_APP_HOST=backend
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: anlix_test_back
    ports:
      - 3001:3001
    restart: on-failure